<<<<<<< HEAD
import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react";
=======
>>>>>>> demo
import { Inter } from "next/font/google";

import "./globals.css";
import React from "react";

<<<<<<< HEAD
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// If loading a variable font, you don't need to specify the font weight
=======
>>>>>>> demo
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>{children}</body>
<<<<<<< HEAD
      <Analytics />
=======
>>>>>>> demo
    </html>
  );
}
